# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b097e53d59a5e2f6267db8dea08518c691abda3cf426a6b4dc8e2ef91605426cf7b25340a7906c78b7564c25d6c6dc67f8f8dc3017e2979e3c80e568ca8461f3

test:
  secret_key_base: 9697fe3804a13339c8fd84195e2ede100dd955c1fcccb6398e8f71060a132668770aef8975c83525fcf7519b184da6f9188bafd6d048a5b81d93a377a85665f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
